version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/" 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Mvc.NewtonsoftJson"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "weekly"
