version: "3.3"

services:

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs,dynamodb,iam,lambda,dynamodbstreams,cloudwatchlogs
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME=localstack
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_DEFAULT_REGION=eu-west-2
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack-config:/docker-entrypoint-initaws.d"
      - "./docker/localstack-config:/opt/code/localstack/files"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"

  sample-api-one:
    container_name: sample-api-one
    build:
      context: ./
      dockerfile: ./docker/sample-api-one/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - Settings:ServiceName=SampleApi.One
      - Settings:AwsServiceUrl=http://localstack:4566
      - Settings:QueueName=sample-api-one
      - Settings:SampleApiTwoTestEndpointUrl=http://sample-api-two:5000/api/test/test
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_DEFAULT_REGION=eu-west-2
    ports:
      - "5123:5000"

  sample-api-two:
    container_name: sample-api-two
    build:
      context: ./
      dockerfile: ./docker/sample-api-two/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - Settings:ServiceName=SampleApi.Two
      - Settings:AwsServiceUrl=http://localstack:4566
      - Settings:TableName=sample-table
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_DEFAULT_REGION=eu-west-2
    ports:
      - "5124:5000"

  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: ./docker/worker/Dockerfile
    environment:
      - Settings:ServiceName=Worker
      - Settings:AwsServiceUrl=http://localstack:4566
      - Settings:QueueName=sample-api-one
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_DEFAULT_REGION=eu-west-2
