version: "3.3"

services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim
    ports: 
      - 9411:9411

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./docker/otel-collector-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317"
      - "55680:55680"
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - zipkin
      - jaeger

  sample-api-one:
    environment:
      - Settings:DistributedTracingOptions:Exporter=OtlpCollector
      - Settings:DistributedTracingOptions:OtlpEndpointUrl=http://otel-collector:55680
      - Settings:DistributedTracingOptions:ZipkinEndpointUrl=

  sample-api-two:
    environment:
      - Settings:DistributedTracingOptions:Exporter=OtlpCollector
      - Settings:DistributedTracingOptions:OtlpEndpointUrl=http://otel-collector:55680
      - Settings:DistributedTracingOptions:ZipkinEndpointUrl=

  worker:
    environment:
      - Settings:DistributedTracingOptions:Exporter=OtlpCollector
      - Settings:DistributedTracingOptions:OtlpEndpointUrl=http://otel-collector:55680
      - Settings:DistributedTracingOptions:ZipkinEndpointUrl=

