version: '3.3'

services:

  localstack:
    container_name: localstack
    build:
      dockerfile: Dockerfile
      context: ./localstack
    environment:
      - SERVICES=sqs,dynamodb,iam,lambda,dynamodbstreams,cloudwatchlogs,s3
      - DEBUG=${DEBUG-}
      - TERRAFORM_ENVIRONMENT=local
      - AWS_DEFAULT_REGION=eu-west-2
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME=localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
