receivers:
  otlp:
    protocols:
      grpc:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: otlp-metrics
    const_labels:
      env: local

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888

service:
  extensions: [pprof, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger,zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]