name: OpenTelemetry upgrade

on:
  push:
    branches:
      - main
  pull_request:
  #  types: [opened]
  workflow_dispatch:

env:
  PR_TITLE_FILTER: 'Bump OpenTelemetry from'
  BRANCH_NAME_FILTER: 'task/opentelemetry-lib-update'

jobs:
  detect-opentelemetry-upgrades:
    outputs:
      status: ${{ steps.check.conclusion }}
      opentelemetry_version: ${{ steps.check.outputs.opentelemetry_version }}
      opentelemetry_library: ${{ steps.check.outputs.opentelemetry_library }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabots Bump OpenTelemetry detected 
        id: check
        if: ${{ startsWith(github.event.pull_request.title, env.PR_TITLE_FILTER) }} && 
            ${{ startsWith(github.event.pull_request.head.ref, env.BRANCH_NAME_FILTER) }} 
        run: | 
            echo "opentelemetry_version=$(echo '${{ github.event.pull_request.title }}' | sed 's/.* //')" >> "$GITHUB_OUTPUT"
            echo "opentelemetry_library=$(echo '${{ github.event.pull_request.title }}' | sed 's/.*Bump //' | cut -f1 -d' ')" >> "$GITHUB_OUTPUT"
            echo "Dependabots Bump OpenTelemetry detected"

  fix-opentelemetry-dependencies: 
    runs-on: ubuntu-latest
    needs: detect-opentelemetry-upgrades
    if: needs.detect-opentelemetry-upgrades.outputs.status == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ env.DOTNET_ENV }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_ENV }}
      - name: Force all ${{ needs.detect-opentelemetry-upgrades.outputs.opentelemetry_library }} libraries on all projects
        run: |
            echo Upgrade to OpenTelemetry ${{ needs.detect-opentelemetry-upgrades.outputs.opentelemetry_version }}
            dotnet add ./MyLambda/MyLambda.csproj package OpenTelemetry --version ${{ needs.detect-opentelemetry-upgrades.outputs.opentelemetry_version }}
            dotnet add ./MyLambda/MyLambda.csproj package OpenTelemetry.Exporter.Zipkin --version ${{ needs.detect-opentelemetry-upgrades.outputs.opentelemetry_version }}
            dotnet add ./MyLambda/MyLambda.csproj package OpenTelemetry.Exporter.OpenTelemetryProtocol --version ${{ needs.detect-opentelemetry-upgrades.outputs.opentelemetry_version }}

      #- name: Check if PR is not hellowolrd
      #  if: ${{ startsWith(github.event.pull_request.title, 'helloworld') }} 
      #  run: echo Title is not helloworld
      #- name: Print branch name
      #  run: echo The branch name ${{ github.event.pull_request.head.ref }}
      #- name: Dump GitHub context
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      #- name: Check if branch is dependabots
      #  if: ${{ startsWith(github.event.pull_request.head.ref, env.BRANCH_NAME_FILTER) }} 
      #  run: echo branch is dependabots
      #- name: Check if PR is not hellowolrd
      #  if: ${{ startsWith(github.event.pull_request.head.ref, 'helloworld') }} 
      #  run: echo branch is not helloworld