name: OpenTelemetry upgrade

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FILTER: 'Bump OpenTelemetry from'

jobs:
  opentelemetry-upgrades:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
      - name: Check if PR is bump OpenTelemetry
        if: startsWith(${{ github.event.pull_request.title }}, ${{ env.FILTER }})
        run: Title is bump open telemetry
      - name: Check if PR is bump OpenTelemetry
        if: startsWith(${{ github.event.pull_request.title }}, 'helloworld')
        run: Title is not helloworld
      - name: Print branch name
        run: echo The branch name ${{ github.ref }}
      