name: OpenTelemetry upgrade

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  opentelemetry-upgrades:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
